{{- if not .Values.netbox.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlan-manager.fullname" . }}-netbox
  labels:
    {{- include "vlan-manager.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  netbox-token: {{ .Values.netbox.token | b64enc | quote }}
{{- end }}
